id: P006827
initial_creation_type: ocr
source_metadata:
  id: bdr:W7972
  title: ཆོས་འབྱུང་མེ་ཏོག་སྙིང་པོ་སྦྲང་རྩིའི་བཅུད
  author: ''
  volumes:
    5702b11d74d34a4eb4da6f7291e4b2a5:
      image_group_id: I1GS55124
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
